services:
  - type: web
    name: truechain-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: FERNET_KEY
        value: YF7w_NVcloZDTNRuzl0zhTDJnf3n_4EbtAL7tpICU7A=
      - key: JWT_SECRET
        value: 4d582cda46945a7974c8440cc7c0d7318d20a7a987bef7405fbf191c5f4621b4
      - key: JWT_EXPIRE_MINUTES
        value: "60"
      - key: AI_TRIAGE_ENABLED
        value: "false"
      - key: CORS_ORIGINS
        value: https://truechain.vercel.app,http://localhost:3000
    disk:
      name: truechain-data
      mountPath: /opt/render/project/src/backend/storage
      sizeGB: 1
